In [99]:
import requests
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [101]:
r = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/search?q=sunflowers')
res = r.json()
object_ids = res['objectIDs']

In [80]:
search_list = [16822570, 2032, 437329, 436524, 20149]
required_objects_list = []

In [89]:
for element in search_list:
    if element in res['objectIDs']:
        required_objects_list.append(element)
required_objects_list

[436524,
 484935,
 437112,
 210191,
 431264,
 397949,
 656530,
 480725,
 486590,
 375281,
 485308,
 705155,
 11922,
 2032,
 816522,
 343052,
 20141,
 208554,
 403496,
 2019,
 360837,
 207869,
 437115,
 400581,
 423400,
 707887,
 223828,
 682927,
 57922,
 649813,
 79739,
 193938,
 339347,
 208218,
 437984,
 202228,
 436534,
 761604,
 437329,
 436252,
 436580,
 363282,
 190739,
 207753,
 437526,
 347980,
 822570,
 487043,
 203893,
 367434,
 423237,
 839296,
 262423,
 367817,
 13644,
 820022,
 648617,
 761731,
 814626,
 207967,
 626832,
 262430,
 262428,
 704667,
 696949,
 707697,
 205386,
 262378,
 426804,
 664519,
 436121,
 436529,
 633526,
 747779,
 369073,
 436144,
 852414,
 427872,
 436530,
 436535,
 437980,
 724844,
 834585,
 834580,
 834765]

In [35]:
objectID = 437980

r_test = requests.get(f'https://collectionapi.metmuseum.org/public/collection/v1/objects/{objectID}')
obj_test = r_test.json()

In [36]:
obj_test

{'objectID': 437980,
 'isHighlight': False,
 'accessionNumber': '49.30',
 'accessionYear': '1949',
 'isPublicDomain': True,
 'primaryImage': 'https://images.metmuseum.org/CRDImages/ep/original/DP130999.jpg',
 'primaryImageSmall': 'https://images.metmuseum.org/CRDImages/ep/web-large/DP130999.jpg',
 'additionalImages': [],
 'constituents': [{'constituentID': 161947,
   'role': 'Artist',
   'name': 'Vincent van Gogh',
   'constituentULAN_URL': 'http://vocab.getty.edu/page/ulan/500115588',
   'constituentWikidata_URL': 'https://www.wikidata.org/wiki/Q5582',
   'gender': ''}],
 'department': 'European Paintings',
 'objectName': 'Painting',
 'title': 'Cypresses',
 'culture': '',
 'period': '',
 'dynasty': '',
 'reign': '',
 'portfolio': '',
 'artistRole': 'Artist',
 'artistPrefix': '',
 'artistDisplayName': 'Vincent van Gogh',
 'artistDisplayBio': 'Dutch, Zundert 1853–1890 Auvers-sur-Oise',
 'artistSuffix': '',
 'artistAlphaSort': 'Gogh, Vincent van',
 'artistNationality': 'Dutch',
 'artistBeginDate': '1853',
 'artistEndDate': '1890',
 'artistGender': '',
 'artistWikidata_URL': 'https://www.wikidata.org/wiki/Q5582',
 'artistULAN_URL': 'http://vocab.getty.edu/page/ulan/500115588',
 'objectDate': '1889',
 'objectBeginDate': 1889,
 'objectEndDate': 1889,
 'medium': 'Oil on canvas',
 'dimensions': '36 3/4 x 29 1/8 in. (93.4 x 74 cm)',
 'measurements': [{'elementName': 'Overall',
   'elementDescription': None,
   'elementMeasurements': {'Height': 93.4, 'Width': 74}},
  {'elementName': 'Frame',
   'elementDescription': None,
   'elementMeasurements': {'Depth': 10.795,
    'Height': 116.2052,
    'Width': 96.5202}},
  {'elementName': 'Other',
   'elementDescription': 'glass',
   'elementMeasurements': {'Height': 94.29769, 'Width': 76.517654}}],
 'creditLine': 'Rogers Fund, 1949',
 'geographyType': '',
 'city': '',
 'state': '',
 'county': '',
 'country': '',
 'region': '',
 'subregion': '',
 'locale': '',
 'locus': '',
 'excavation': '',
 'river': '',
 'classification': 'Paintings',
 'rightsAndReproduction': '',
 'linkResource': '',
 'metadataDate': '2022-03-10T05:08:29.907Z',
 'repository': 'Metropolitan Museum of Art, New York, NY',
 'objectURL': 'https://www.metmuseum.org/art/collection/search/437980',
 'tags': [{'term': 'Landscapes',
   'AAT_URL': 'http://vocab.getty.edu/page/aat/300132294',
   'Wikidata_URL': 'https://www.wikidata.org/wiki/Q191163'},
  {'term': 'Cypresses',
   'AAT_URL': 'http://vocab.getty.edu/page/aat/300343641',
   'Wikidata_URL': 'https://www.wikidata.org/wiki/Q146911'}],
 'objectWikidata_URL': 'https://www.wikidata.org/wiki/Q867510',
 'isTimelineWork': True,
 'GalleryNumber': '825'}

### Определение картин с японской культурой

In [110]:
response = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/search?q=sunflowers')
response_json = r.json()
object_ids = res['objectIDs']


required_columns = [
    'objectID', 
    'title', 
    'artistDisplayName', 
    'department', 
    'objectBeginDate', 
    'objectEndDate',
    'period',
    'objectName',
    'culture',
]

paintings_df = pd.DataFrame()
for object_id in object_ids:
    response = requests.get(f'https://collectionapi.metmuseum.org/public/collection/v1/objects/{object_id}')
    response_json = response.json()
    values_list = []
    values_dict = {}
    for data_key in required_columns:
        try:
            values_dict[data_key] = [response_json[data_key]]
        except:
            print(f'object_id - {object_id} could not be found in database')
            break
    current_df = pd.DataFrame(data=values_dict)
    paintings_df = pd.concat([paintings_df, current_df], ignore_index=True)

85
object_id - 839296 could not be found in database
object_id - 704667 could not be found in database
object_id - 696949 could not be found in database

In [113]:
paintings_df.head()

,objectID,title,artistDisplayName,department,objectBeginDate,objectEndDate,period,objectName,culture
0,436524,Sunflowers,Vincent van Gogh,European Paintings,1887,1887,,Painting,
1,484935,Sunflowers,Edward McKnight Kauffer,Modern and Contemporary Art,1921,1921,,Painting,
2,437112,Bouquet of Sunflowers,Claude Monet,European Paintings,1881,1881,,Painting,
3,210191,Vase with sunflowers,Rozenburg Plateelfabriek,European Sculpture and Decorative Arts,1896,1896,,Vase,
4,431264,Sunflowers,Lily Converse,Drawings and Prints,1941,1941,,Print,

In [114]:
paintings_df.query('culture == "Japan"')

,objectID,title,artistDisplayName,department,objectBeginDate,objectEndDate,period,objectName,culture
28,57922,Incense box,,Asian Art,1700,1799,Edo period (1615–1868),Incense box,Japan

### Определение периода с наибольшим количеством работ

In [127]:
dep6_cat_response = requests.get('https://collectionapi.metmuseum.org/public/collection/v1/search?departmentId=6&q=cat')
cats = dep6_cat_response.json()
cats_IDs = cats['objectIDs'][:1000]
len(cats_IDs)

1000

In [128]:
required_columns = [
    'objectID', 
    'title', 
    'artistDisplayName', 
    'department', 
    'objectBeginDate', 
    'objectEndDate',
    'period',
    'objectName',
    'culture',
]

cat_paintings_df = pd.DataFrame()
for object_id in cats_IDs:
    response = requests.get(f'https://collectionapi.metmuseum.org/public/collection/v1/objects/{object_id}')
    response_json = response.json()
    values_list = []
    values_dict = {}
    for data_key in required_columns:
        try:
            values_dict[data_key] = [response_json[data_key]]
        except:
            print(f'object_id - {object_id} could not be found in database')
            break
    current_df = pd.DataFrame(data=values_dict)
    cat_paintings_df = pd.concat([cat_paintings_df, current_df], ignore_index=True)

In [129]:
cat_paintings_df.head()

,objectID,title,artistDisplayName,department,objectBeginDate,objectEndDate,period,objectName,culture
0,49698,Cat,Zhang Yuguang,Asian Art,1900,1968,,Folding fan mounted as an album leaf,China
1,49470,Cat,Wang Li,Asian Art,1813,1879,Qing dynasty (1644–1911),Hanging scroll,China
2,53222,Musk Cat,Uto Gyoshi,Asian Art,1550,1599,Muromachi period (1392–1573),Hanging scroll,Japan
3,36221,Cat,Wang Yun,Asian Art,1900,1933,,Hanging scroll,China
4,60873,Burial Crown,,Asian Art,960,1279,Song dynasty (960–1279) or later,Burial crown,China

In [130]:
cat_paintings_df.period.value_counts()

Edo period (1615–1868)                                          435
                                                                 96
Ming dynasty (1368–1644)                                         50
Qing dynasty (1644–1911)                                         49
Muromachi period (1392–1573)                                     32
                                                               ...
Early Malla period                                                1
Ming Dynasty (1368–1644)                                          1
Qing dynasty (1644–1911), Qianlong mark and period (1736–95)      1
Northern Wei dynasty (386–524)                                    1
Mughal period (1526–1858)                                         1
Name: period, Length: 119, dtype: int64